on:
  push:
    branches:
      - implement-ndtc-api
name: 🚀 Deploy website on push staging
jobs:
  web-deploy:
    name: 🎉 Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Deploy to the first server
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}
